/*
 * generated by Xtext 2.11.0
 */
package com.autology.language.ide


/**
 * Use this class to register ide components.
 */
class AutologyScriptIdeModule extends AbstractAutologyScriptIdeModule {
}
