language: java
jdk:
  - oraclejdk8
sudo: true # Required or unit tests seems to fail for some reason?
before_install:
 - export GRADLE_OPTS="-Xmx128m" # Might as well not waste memory
 - ./.travis/debug-memory.sh &
install:
 - ./gradlew assemble
script:
 - travis_retry ./gradlew check
after_success:
 - ./gradlew jacocoTestReport
 - bash <(curl -s https://codecov.io/bash)
 - ./gradlew coveralls
cache:
  directories: # Speed up dependency resolution
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.embedmongo
