language: java
jdk:
  - oraclejdk8
sudo: true # Required or unit tests seems to fail for some reason?
after_success:
 - ./gradlew jacocoTestReport
 - bash <(curl -s https://codecov.io/bash)
 - ./gradlew coveralls
cache:
  directories:
  - $HOME/.m2 # Speed up dependency resolution
  - $HOME/.gradle # Speed up dependency resolution
