/*
 * generated by Xtext 2.11.0
 */
package net.opensorcerers.language.ide


/**
 * Use this class to register ide components.
 */
class AutologyScriptIdeModule extends AbstractAutologyScriptIdeModule {
}
