/*
 * generated by Xtext 2.11.0
 */
package net.opensorcerers.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AutologyScriptRuntimeModule extends AbstractAutologyScriptRuntimeModule {
}
