/*
 * generated by Xtext 2.11.0
 */
package com.autology.language.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class AutologyScriptWebModule extends AbstractAutologyScriptWebModule {
}
