/*
 * generated by Xtext 2.11.0
 */
package com.autology.language.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class AutologyScriptScopeProvider extends AbstractAutologyScriptScopeProvider {

}
